### ISSUE TITLE
compiiile unusable - incomplete build

### ISSUE THREAD

**Issue by decima** [compiiile/compiiile#58]
repo for testing : https://github.com/decima/tmp-courses-compiiile

I'm giving up on compiiile for now due to the short time.

**Comment by decima** [comment]
it's not a build issue, it's a link issue, it doesn't use host nor a base-url by default. my bad.

**Comment by AlbanCrepel** [comment]
Hey @decima , you can get a fully working version of your code with the links I fixed on the Pull Request I've just submitted : https://github.com/decima/tmp-courses-compiiile/pull/1 

The print integration is also working on the `/print` page (with a blank first page since the `README` is blank).

I hope that will resolve all your issues :sparkles:
